import { definePages } from "@/lib/content/types";

const commonFaq = [
  {
    question: "Faut-il un permis de conduire pour louer un scooter ?",
    answer: "Oui. Le conducteur et tout conducteur supplémentaire doivent présenter un permis original, valable en Italie et adapté au modèle 50cc ou 125cc choisi, ainsi qu’un passeport ou une carte d’identité en cours de validité. La catégorie du permis, l’âge et l’éligibilité sont vérifiés avant confirmation.",
  },
  {
    question: "Tous les scooters peuvent-ils transporter deux personnes ?",
    answer: "La flotte est prévue pour voyager à deux : les scooters seront homologués pour un conducteur et un passager et fournis avec deux casques, un top case et un antivol ou bloque-disque. Le modèle et les équipements seront toujours précisés dans votre confirmation.",
  },
  {
    question: "Où ont lieu le retrait et la restitution ?",
    answer: "Le retrait est prévu dans une base près de Viale Alghero à Bosa. Nous étudions aussi la livraison et la récupération auprès des hébergements de Bosa et Bosa Marina : indiquez-nous où vous séjournez pour nous aider à définir le service. La disponibilité et le coût hors de cette zone seront étudiés sur demande.",
  },
  {
    question: "Quels sont le kilométrage inclus et la caution ?",
    answer: "La durée minimale de location est de 24 heures et comprend 150 km, même si vous n’utilisez le scooter que quatre heures. La formule de 7 jours comprend 900 km. Chaque kilomètre supplémentaire coûte 0,25 €. Une caution de 500 € par scooter est prévue ; ses modalités de paiement et de restitution seront confirmées avant la location.",
  },
  {
    question: "Quelles garanties sont incluses ?",
    answer: "La formule en cours de définition comprend la responsabilité civile pour véhicule de location sans chauffeur, les dommages aux tiers, la couverture du passager dans les limites du contrat, la garantie accident du conducteur, le vol et l’incendie, les dommages accidentels ou de collision et l’assistance routière. Les plafonds, exclusions et franchises seront confirmés par écrit avant la location.",
  },
  {
    question: "Quelle est la politique de carburant ?",
    answer: "La règle est plein-plein : vous recevez le scooter avec le réservoir plein et le restituez avec le plein. Les conditions définitives sont récapitulées avant le retrait.",
  },
];

export const frPages = definePages([
  {
    slug: "",
    alternateSlug: "",
    kind: "home",
    title: "Bosa in Scooter | Location de scooters 50cc et 125cc",
    h1: "Découvrez Bosa en toute liberté",
    description: "Louez un scooter 50cc ou 125cc pour découvrir Bosa, Bosa Marina et la côte en toute liberté. Découvrez le service et demandez les disponibilités.",
    eyebrow: "Scooters 50cc et 125cc · Bosa",
    primaryKeyword: "scooter à Bosa",
    intro: "Du centre historique aux plages, choisissez où vous arrêter et quand repartir. Nous préparons un service de location de scooters 50cc et 125cc pour découvrir Bosa sans dépendre d’une voiture.",
    sections: [
      {
        heading: "Plus de liberté chaque jour",
        body: ["Partez à la plage, revenez dîner dans le centre historique et explorez la côte à votre rythme. Bosa in Scooter est pensé pour faciliter chaque trajet et laisser plus de place à vos vacances."],
        bullets: ["50cc et 125cc pour chaque itinéraire", "Deux places et deux casques inclus", "Des conditions claires, sans surprise"],
      },
      {
        heading: "Une location adaptée à votre séjour",
        body: ["Choisissez 24 heures, 7 jours ou davantage et indiquez-nous vos dates, votre itinéraire et votre lieu de séjour. Les demandes reçues nous aideront à définir les disponibilités et les formules avant l’ouverture des réservations."],
        bullets: ["Retrait prévu près de Viale Alghero", "Livraison et récupération à l’étude", "Deux casques, top case et antivol prévus"],
      },
    ],
    faq: commonFaq.slice(0, 4),
  },
  {
    slug: "location-scooter-bosa",
    alternateSlug: "scooter-rental-bosa",
    kind: "commercial",
    title: "Location de scooter à Bosa | 50cc et 125cc",
    h1: "Location de scooters 50cc et 125cc à Bosa",
    description: "Découvrez la location de scooters 50cc et 125cc à Bosa : tarifs, équipements, retrait et livraison. Demandez les disponibilités sans engagement.",
    eyebrow: "Bosa à votre rythme",
    primaryKeyword: "location scooter Bosa",
    intro: "Le centre historique, Bosa Marina et la côte sont plus proches lorsque vous voyagez à votre rythme. Choisissez votre scooter et indiquez vos dates : votre demande est sans engagement et nous aide à préparer le lancement du service.",
    sections: [
      {
        heading: "La flotte",
        body: ["La flotte est conçue autour de scooters 50cc et 125cc, tous homologués pour un conducteur et un passager. Nous vous aiderons à choisir le modèle adapté à votre permis, votre expérience et votre itinéraire."],
        bullets: ["Deux casques", "Top case", "Antivol ou bloque-disque", "Un conducteur supplémentaire enregistré"],
      },
      {
        heading: "Ce qui est inclus",
        body: ["Les tarifs publiés sont prévus pour inclure la TVA, les équipements, la politique plein-plein et les garanties indiquées. Avant toute location, vous recevrez les disponibilités et l’ensemble des conditions par écrit."],
        bullets: ["Responsabilité civile et dommages aux tiers", "Couverture du passager et accident du conducteur", "Vol, incendie et collision", "Assistance routière"],
      },
      {
        heading: "Documents nécessaires",
        body: ["Vous devez présenter un permis original valable en Italie et adapté au scooter choisi, ainsi qu’une carte d’identité ou un passeport en cours de validité. Les mêmes documents sont exigés pour tout conducteur supplémentaire."],
      },
      {
        heading: "Du centre historique à la marina",
        body: ["Un scooter rend les trajets quotidiens plus souples et permet de répartir votre visite entre quartiers, plages et commerces locaux. Choisissez le modèle selon votre expérience, votre itinéraire et les conditions du jour."],
      },
    ],
    faq: commonFaq,
  },
  {
    slug: "location-scooter-bosa-marina",
    alternateSlug: "scooter-rental-bosa-marina",
    kind: "commercial",
    title: "Location de scooter à Bosa Marina | Disponibilités",
    h1: "Des scooters pour Bosa Marina",
    description: "Scooters 50cc et 125cc pour circuler entre Bosa Marina, le centre historique et la côte. Demandez les disponibilités et choisissez retrait ou livraison.",
    eyebrow: "De la mer au centre historique",
    primaryKeyword: "location scooter Bosa Marina",
    intro: "Vous séjournez à Bosa Marina ? Indiquez vos dates et la zone de votre hébergement. Nous définissons la solution la plus pratique entre le retrait à la base et la livraison sur votre lieu de séjour.",
    sections: [
      {
        heading: "Votre scooter là où vous en avez besoin",
        body: ["Les tarifs à l’étude sont de 20 à 25 € pour une livraison ou une récupération uniquement à Bosa et Bosa Marina, et de 35 à 45 € pour les deux trajets. Indiquez votre lieu de séjour pour nous aider à organiser un service réellement utile."],
        bullets: ["Retrait prévu à Bosa", "Livraison à l’hébergement à l’étude", "Disponibilité confirmée avant la location"],
      },
      {
        heading: "Livraison incluse pour les longs séjours",
        body: ["Nous souhaitons inclure la livraison pour les locations d’au moins 10 jours, ou pour deux scooters loués au moins 7 jours. Envoyez-nous vos dates : les demandes nous aideront à évaluer et confirmer cette formule."],
      },
      {
        heading: "Entre la marina, le centre historique et la côte",
        body: ["Un scooter permet de combiner mer, centre historique et commerces locaux sans organiser chaque journée autour d’un seul point de départ. La météo, l’état des routes et votre expérience doivent toujours guider votre choix."],
      },
    ],
    faq: commonFaq,
  },
  {
    slug: "tarifs",
    alternateSlug: "prices",
    kind: "prices",
    title: "Prix location scooter Bosa | Tarifs 50cc et 125cc",
    h1: "Tarifs et formules de location",
    description: "Tarifs prévus pour la location de scooter à Bosa pendant 24 heures ou 7 jours, avec kilométrage, caution, livraison et récupération.",
    eyebrow: "Des tarifs transparents",
    primaryKeyword: "prix location scooter Bosa",
    intro: "Consultez nos tarifs de lancement provisoires et indiquez vos dates. Votre demande est sans engagement : les disponibilités et les conditions seront confirmées par écrit avant toute location.",
    sections: [
      {
        heading: "Kilométrage inclus",
        body: ["La location minimale de 24 heures comprend 150 km ; le même tarif s’applique même si le scooter n’est utilisé que quatre heures. La formule de 7 jours comprend 900 km. Au-delà du forfait, le tarif est de 0,25 €/km."],
        bullets: ["Location minimale : 24 heures", "Locations de 2 à 6 jours : tarif sur demande", "En dehors de mai à octobre : tarif sur demande"],
      },
      {
        heading: "Caution et prestations incluses",
        body: ["La caution prévue est de 500 € par scooter. Les tarifs incluent la TVA, un conducteur supplémentaire enregistré, deux casques, un top case, un antivol, la politique plein-plein et les garanties indiquées. Chaque élément sera confirmé dans les conditions définitives."],
      },
      {
        heading: "Livraison et récupération",
        body: ["Le retrait à la base de Bosa est prévu sans supplément. Pour Bosa et Bosa Marina, nous étudions un tarif de 20 à 25 € pour la livraison ou la récupération uniquement, et de 35 à 45 € pour les deux. La disponibilité et le coût hors de cette zone seront étudiés sur demande."],
      },
    ],
    faq: commonFaq.slice(2),
  },
  {
    slug: "comment-ca-marche",
    alternateSlug: "how-it-works",
    kind: "info",
    title: "Comment louer un scooter | Bosa in Scooter",
    h1: "Comment ça marche",
    description: "Comment demander un scooter 50cc ou 125cc à Bosa : indiquez vos dates et vos besoins, puis recevez une notification à l’ouverture des réservations.",
    eyebrow: "Quatre étapes simples",
    primaryKeyword: "comment louer un scooter à Bosa",
    intro: "En quelques étapes simples, indiquez-nous le scooter dont vous avez besoin et les dates de votre séjour. À ce stade, votre demande ne crée ni réservation ni paiement.",
    sections: [
      { heading: "1. Indiquez-nous votre arrivée", body: ["Sélectionnez vos dates, le nombre de scooters et votre lieu de séjour. Aucun document ni moyen de paiement n’est nécessaire."] },
      { heading: "2. Choisissez votre scooter", body: ["Préférez-vous un 50cc pour le centre historique et la marina, ou un 125cc pour aller plus loin ? Votre permis, votre expérience et votre itinéraire nous aident à recommander le bon modèle."] },
      { heading: "3. Demandez à être informé", body: ["Si vous souhaitez connaître la date d’ouverture des réservations, vous pouvez laisser votre adresse e-mail et consentir à être contacté."] },
      { heading: "4. Recevez la confirmation", body: ["Lorsque le service sera disponible, nous confirmerons par écrit le scooter, les tarifs, le retrait ou la livraison et toutes les conditions avant tout engagement."] },
    ],
    faq: commonFaq,
  },
  {
    slug: "questions-frequentes",
    alternateSlug: "faq",
    kind: "info",
    title: "FAQ location scooter Bosa | Bosa in Scooter",
    h1: "Questions fréquentes",
    description: "Permis, documents, passager, caution, assurance, carburant, retrait et livraison pour la location de scooter à Bosa.",
    eyebrow: "Avant de prendre la route",
    primaryKeyword: "questions location scooter Bosa",
    intro: "Retrouvez les informations essentielles pour choisir sereinement. Le service est en cours de validation : les disponibilités et les conditions seront confirmées par écrit avant toute location.",
    sections: [
      {
        heading: "Une confirmation claire avant la location",
        body: ["N’envoyez aucun document d’identité ni moyen de paiement via le formulaire. Nous demanderons les documents nécessaires par le canal convenu et fournirons toutes les conditions par écrit."],
      },
    ],
    faq: commonFaq,
  },
  {
    slug: "contact",
    alternateSlug: "contact",
    kind: "contact",
    title: "Demander les disponibilités | Bosa in Scooter",
    h1: "Demandez votre scooter à Bosa",
    description: "Indiquez vos dates, le modèle souhaité et votre lieu de séjour. Votre demande est gratuite, sans engagement et nous aide à préparer le service.",
    eyebrow: "Demande gratuite · sans engagement",
    primaryKeyword: "contact location scooter Bosa",
    intro: "Indiquez-nous vos dates et le scooter souhaité. Bosa in Scooter est actuellement en cours de validation : le formulaire ne crée pas de réservation, mais nous aide à construire le service selon les besoins réels des visiteurs.",
    sections: [
      {
        heading: "Quelques minutes suffisent",
        body: ["Sélectionnez vos dates, le nombre de scooters, le modèle et votre lieu de séjour. Nous ne demandons ni nom, ni document, ni moyen de paiement ; l’adresse e-mail est facultative et utilisée uniquement si vous souhaitez être informé du lancement."],
      },
    ],
  },
  {
    slug: "guides",
    alternateSlug: "guides",
    kind: "info",
    title: "Guides locaux de Bosa | Bosa in Scooter",
    h1: "Guides locaux",
    description: "Guides et conseils pratiques pour circuler entre Bosa, Bosa Marina, les plages et la côte, avec ou sans voiture pendant votre séjour.",
    eyebrow: "Explorez les environs",
    primaryKeyword: "guides locaux Bosa",
    intro: "Quatre guides pratiques pour choisir vos déplacements, préparer une journée à la plage et évaluer les itinéraires plus longs.",
    sections: [
      {
        heading: "Choisissez un guide",
        body: ["Commencez par le type de journée que vous préparez : rester en ville, circuler entre Bosa et la marina, rejoindre une plage ou suivre la route côtière."],
        bullets: ["Visiter Bosa sans voiture", "Circuler entre le centre historique et la marina", "Rejoindre les plages proches", "Évaluer la route Bosa–Alghero"],
      },
    ],
  },
  {
    slug: "guides/visiter-bosa-sans-voiture",
    alternateSlug: "guides/visit-bosa-without-a-car",
    kind: "guide",
    title: "Visiter Bosa sans voiture | Guide des déplacements",
    h1: "Visiter Bosa sans voiture",
    description: "Comment organiser l’arrivée, les bagages et les déplacements entre le centre historique, Bosa Marina et la côte pendant un séjour sans voiture à Bosa.",
    eyebrow: "Guide local",
    primaryKeyword: "visiter Bosa sans voiture",
    intro: "Un séjour sans voiture est plus simple lorsque l’arrivée, les bagages et les déplacements quotidiens sont organisés séparément.",
    sections: [
      { heading: "Choisir où séjourner", body: ["Le centre historique est idéal pour rejoindre à pied restaurants et sites touristiques ; Bosa Marina est plus pratique pour la plage. Votre point de départ détermine les trajets quotidiens qui nécessitent un moyen de transport."] },
      { heading: "Organiser l’arrivée et les bagages", body: ["Pour votre arrivée, utilisez les transports en commun, un transfert ou une livraison organisée. Le scooter est utile une fois les bagages déposés à l’hébergement, mais ne remplace pas un transfert de bagages."] },
      { heading: "Choisir la bonne solution pour chaque trajet", body: ["Marchez dans le centre historique, utilisez un scooter pour la marina et la côte proche, et choisissez une voiture ou un transfert pour les longs trajets ou les bagages volumineux."], sources: [{ label: "Lignes et horaires ARST", href: "https://www.arstspa.info/" }] },
    ],
    faq: commonFaq.slice(0, 3),
  },
  {
    slug: "guides/se-deplacer-a-bosa",
    alternateSlug: "guides/getting-around-bosa",
    kind: "guide",
    title: "Se déplacer à Bosa et Bosa Marina",
    h1: "Se déplacer à Bosa",
    description: "Comparaison pratique de la marche, des transports en commun et du scooter dans le centre de Bosa et vers Bosa Marina.",
    eyebrow: "Guide local",
    primaryKeyword: "se déplacer à Bosa",
    intro: "Bosa est compacte, mais les pentes, la chaleur et la distance jusqu’à la marina peuvent rendre un moyen de transport utile.",
    sections: [
      { heading: "Le centre historique à pied", body: ["La marche est la solution la plus simple dans les rues historiques, le long du fleuve et autour des restaurants du centre. Depuis 2026, la commune indique des places payantes dans plusieurs rues du centre et, en saison, à Bosa Marina."], sources: [{ label: "Stationnement — Commune de Bosa", href: "https://comune.bosa.or.it/argomento/parcheggi/" }] },
      { heading: "Entre le centre historique et Bosa Marina", body: ["Un scooter facilite les allers-retours à la plage ou les retours en soirée, surtout en été et pour les hébergements situés hors du centre."] },
      { heading: "50cc ou 125cc", body: ["Un 50cc convient au village médiéval et aux lieux de baignade proches. Un 125cc est plus adapté aux villages voisins et aux criques plus éloignées, sous réserve du permis et des conditions de location."] },
    ],
    faq: commonFaq.slice(0, 3),
  },
  {
    slug: "guides/plages-pres-bosa-scooter",
    alternateSlug: "guides/beaches-near-bosa-by-scooter",
    kind: "guide",
    title: "Plages près de Bosa en scooter | Guide local",
    h1: "Les plages près de Bosa en scooter",
    description: "Comment évaluer Bosa Marina, s’Abba Druche, Portu Managu, Turas et Compoltitu selon l’accès routier, le stationnement et les conditions.",
    eyebrow: "Guide local",
    primaryKeyword: "plages près de Bosa en scooter",
    intro: "Choisissez votre plage selon la distance, l’état des routes et le kilométrage inclus dans la location.",
    sections: [
      { heading: "Choisir la côte pour la journée", body: ["Bosa Marina est l’option la plus simple pour rester près des services. Pour rejoindre s’Abba Druche, Portu Managu, Turas ou Compoltitu, vérifiez l’accès, le type de route et le stationnement. Suivez toujours les informations sur place, car les accès et services saisonniers peuvent changer."], sources: [{ label: "Bosa — SardegnaTurismo", href: "https://www.sardegnaturismo.it/fr/lieux/nord-ouest/bosa" }, { label: "Stationnement — Commune de Bosa", href: "https://comune.bosa.or.it/argomento/parcheggi/" }] },
      { heading: "Préparer le scooter", body: ["Emportez de l’eau et une protection solaire, ne rangez dans le top case que des objets adaptés et sécurisez le scooter avec l’antivol ou le bloque-disque fourni."] },
      { heading: "Prévoir le stationnement et le retour", body: ["Utilisez les zones prévues, évitez le sable et les sols instables et prévoyez le temps nécessaire pour faire le plein avant la restitution ou la récupération convenue."] },
    ],
    faq: commonFaq.slice(1, 6),
  },
  {
    slug: "guides/itineraire-scooter-bosa-alghero",
    alternateSlug: "guides/bosa-alghero-scooter-route",
    kind: "guide",
    title: "Bosa–Alghero en scooter | Guide de la route côtière",
    h1: "De Bosa à Alghero en scooter",
    description: "Comment évaluer la route côtière SP 49 de Bosa à Alghero : scooter, expérience, vent, kilométrage et marge pour le retour.",
    eyebrow: "Guide local",
    primaryKeyword: "itinéraire scooter Bosa Alghero",
    intro: "La route côtière est spectaculaire, mais plus longue et plus exposée que les trajets locaux autour de Bosa.",
    sections: [
      { heading: "Vérifier que le véhicule convient", body: ["Demandez si le scooter choisi est adapté à l’itinéraire, à votre permis et à votre expérience, surtout si vous voyagez avec un passager."] },
      { heading: "Calculer le trajet complet", body: ["Comptez l’aller-retour, les déplacements locaux à Alghero et une marge de sécurité par rapport au kilométrage inclus dans votre formule."] },
      { heading: "Décider selon les conditions", body: ["La SP 49 longe une portion de côte sinueuse et exposée dans la région de Capo Marrargiu. Vent fort, chaleur, circulation et faible luminosité peuvent changer l’expérience ; choisissez un itinéraire plus court ou un autre moyen de transport lorsque les conditions sont mauvaises."], sources: [{ label: "Sur la route le long de la côte — SardegnaTurismo", href: "https://www.sardegnaturismo.it/fr/en-moto-le-long-de-la-cote" }, { label: "Capo Marrargiu — SardegnaTurismo", href: "https://www.sardegnaturismo.it/fr/explorer/capo-marrargiu" }] },
    ],
    faq: commonFaq.slice(0, 5),
  },
  {
    slug: "confidentialite",
    alternateSlug: "privacy",
    kind: "info",
    title: "Politique de confidentialité | Bosa in Scooter",
    h1: "Politique de confidentialité",
    description: "Traitement des données dans le cadre de la validation de Bosa in Scooter et de la demande de contact facultative.",
    eyebrow: "Article 13 du RGPD",
    primaryKeyword: "confidentialité Bosa in Scooter",
    intro: "Cette notice explique quelles données le site collecte, pourquoi elles sont traitées, combien de temps elles sont conservées et comment exercer vos droits.",
    sections: [
      { heading: "Responsable du traitement", body: [] },
      {
        heading: "Données, finalités et bases juridiques",
        body: [
          "Pour valider le projet, nous recueillons la période souhaitée, le nombre de scooters, la tranche d’âge, la préférence 50cc/125cc, le lieu de séjour, la macro-région d’origine et l’ancienneté du permis supérieure ou non à cinq ans. Nous ne demandons ni nom, ni âge exact, ni adresse, ni document. Un champ de notes facultatif est disponible, limité à 500 caractères et ne doit contenir aucune donnée sensible.",
          "Les réponses sont conçues pour ne pas identifier directement une personne et servent à mesurer la demande, la saisonnalité et l’intérêt pour le service. Ces données et les métadonnées techniques nécessaires à la fourniture, à la sécurité et à la prévention des abus sont traitées sur la base des intérêts légitimes du responsable, conformément à l’article 6, paragraphe 1, point f) du RGPD, après évaluation de la nécessité et mise en balance des intérêts.",
          "En tant qu’hébergeur, Vercel peut traiter pour chaque visiteur l’adresse IP, la localisation approximative déduite de l’adresse IP, l’URL et les paramètres de la requête, la date et l’heure, le statut de la réponse, la région d’exécution et le user-agent. Ces données ne sont pas ajoutées à la réponse de recherche et ne sont pas utilisées par le responsable à des fins de profilage ou de publicité.",
          "Si vous demandez volontairement à être contacté, nous recueillons votre adresse e-mail sur la base de votre consentement, conformément à l’article 6, paragraphe 1, point a). Ce consentement est distinct, facultatif et révocable. Si vous formulez ensuite une demande précise de disponibilité ou d’information, les données nécessaires peuvent être traitées afin de prendre des mesures précontractuelles à votre demande, conformément à l’article 6, paragraphe 1, point b).",
          "L’espace d’administration est réservé à un seul compte GitHub autorisé. L’identifiant GitHub, le nom, l’adresse e-mail, le statut de vérification de l’e-mail, l’image de profil, les autorisations et jetons OAuth chiffrés, le jeton et les dates de session, l’adresse IP et le user-agent sont traités à des fins d’authentification, de contrôle des accès et de sécurité. La base juridique est l’intérêt légitime du responsable à protéger et administrer le service, conformément à l’article 6, paragraphe 1, point f) du RGPD.",
        ],
      },
      { heading: "Données obligatoires et facultatives", body: ["Les champs sans identifiant direct et la confirmation de lecture de la notice sont nécessaires pour envoyer une réponse. Les notes, la demande de contact, l’adresse e-mail et le consentement associé restent facultatifs. Sans demande de contact, le formulaire n’affiche ni n’envoie aucune adresse e-mail.", "Les données OAuth et de session sont nécessaires uniquement à l’administrateur qui choisit d’accéder à l’espace réservé ; le site public ne nécessite pas de compte GitHub."] },
      { heading: "Destinataires et prestataires", body: ["Les réponses et demandes de contact sont accessibles uniquement au responsable via un tableau de bord protégé ; elles ne sont ni vendues ni utilisées à des fins publicitaires. Les prestataires techniques ne peuvent traiter que les données nécessaires aux services de base de données, d’hébergement, de sécurité et d’authentification, selon les rôles et accords décrits ci-dessous."] },
      { heading: "Transferts hors de l’EEE", body: ["La base de données est configurée dans la région indiquée ci-dessus. Vercel utilise un réseau edge mondial et GitHub traite aussi des données aux États-Unis et dans d’autres pays. Selon le service et l’accord applicable, les transferts soumis au RGPD reposent sur des décisions d’adéquation, comme le cadre de protection des données UE–États-Unis, et/ou sur les clauses contractuelles types de la Commission européenne.", "Le formulaire reste désactivé tant que les garanties effectivement vérifiées pour le prestataire de la base de données ne sont pas configurées."] },
      { heading: "Conservation et suppression", body: ["Les réponses brutes sont utilisées pour l’étude de marché et font l’objet d’un examen documenté de leur nécessité au moins tous les 24 mois. Si un enregistrement individuel n’est plus nécessaire, il est supprimé ou transformé en données agrégées réellement anonymes. Les statistiques irréversiblement anonymes peuvent être conservées sans durée fixe.", "Les adresses e-mail ne sont conservées que le temps nécessaire pour communiquer la disponibilité du service ou jusqu’au retrait du consentement. Leur nécessité est réévaluée au moins tous les 24 mois ; si la finalité n’est plus actuelle, l’adresse est supprimée ou un nouveau consentement est demandé. L’absence de demande de suppression ne justifie pas une conservation illimitée.", "Les sessions administratives expirent après huit heures et peuvent être renouvelées pendant leur utilisation. Elles sont supprimées à la déconnexion ou, une fois expirées, lors de la prochaine requête administrative ou OAuth. Les enregistrements de vérification OAuth expirés sont supprimés de la même manière. Le profil GitHub, le compte lié et les jetons OAuth chiffrés sont conservés tant que l’accès administratif reste autorisé et nécessaire.", "Les journaux techniques de Vercel suivent la durée de conservation native de l’abonnement actif et ne sont pas exportés via Log Drain. Toute modification de l’abonnement, de la durée de conservation ou de la destination des journaux exige une nouvelle évaluation et la mise à jour de cette notice."] },
      { heading: "Droits et retrait du consentement", body: ["Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, vous opposer au traitement et, le cas échéant, demander la portabilité. Vous pouvez retirer à tout moment votre consentement au contact en écrivant au responsable ; ce retrait n’affecte pas la licéité du traitement effectué avant celui-ci.", "Vous pouvez déposer une réclamation auprès du Garante per la protezione dei dati personali, l’autorité italienne de protection des données. Les réponses sans adresse e-mail ne contiennent pas d’identifiant direct, mais les dates, lieux, horodatages ou notes peuvent néanmoins constituer des données personnelles. S’il n’existe pas assez d’informations pour retrouver une réponse, une demande portant sur celle-ci peut ne pas être techniquement réalisable."] },
      { heading: "Cookies et mesure d’audience", body: ["Le site n’installe aucun outil d’analyse tiers ni cookie non essentiel. L’espace d’administration utilise un cookie de session propriétaire, HttpOnly, Secure en production et SameSite=Lax, qui expire après huit heures, ainsi qu’un cookie temporaire protégeant le flux OAuth. Ces cookies sont strictement nécessaires et ne servent ni au profilage ni à la publicité.", "Avant d’introduire un outil non essentiel, une solution d’analyse ou tout autre suivi, cette notice devra être mise à jour et, lorsque cela est requis, un choix valable devra être recueilli auprès de l’utilisateur."] },
      { heading: "Mises à jour", body: ["Cette notice doit être mise à jour en cas de changement du responsable, des coordonnées, des prestataires, des finalités, des bases juridiques, des durées de conservation ou des technologies de suivi. Dernière révision organisationnelle : 4 août 2026."] },
    ],
  },
], { publishedAt: "2026-08-02", lastModified: "2026-08-04" });
