import type { PageContent } from "@/lib/content/types";

const faq = [
  { question: "Which licence do I need for a 125cc scooter?", answer: "Requirements depend on your licence, age and the provider’s terms. They must be checked in writing before you confirm." },
  { question: "Can two people ride the scooter?", answer: "Only when the vehicle is approved for two and the rider meets all applicable requirements. This will be confirmed with the proposed model." },
  { question: "Where is pickup?", answer: "The pickup point has not been finalised. Add your accommodation to the request and you will receive a transparent proposal." },
  { question: "Are deposit and insurance included?", answer: "Deposit, coverage, excess and other conditions will be confirmed with the quote. We do not publish terms that are not yet defined." },
];

export const enPages: PageContent[] = [
  { slug:"", alternateSlug:"", kind:"home", title:"Scooters in Bosa | Check availability", h1:"See more of Bosa, on your own schedule", description:"Discover a 125cc scooter service being prepared in Bosa. Send a no-obligation availability request.", eyebrow:"Bosa · Western Sardinia", primaryKeyword:"scooters in Bosa", intro:"A straightforward way to connect the old town, Bosa Marina and the coast—without pretending the service is already fully operational.", sections:[{heading:"Why explore Bosa by scooter",body:["A compact scooter can make local travel more flexible. Your enquiry is not an automatic booking: it lets us verify the actual vehicle, price and pickup arrangements."],bullets:["125cc model to be confirmed","No-obligation enquiry","Written quote and conditions"]},{heading:"Plan before you arrive",body:["Share your dates, party size and accommodation. You will receive a clear answer without invented prices or promises."]}], faq:faq.slice(0,3)},
  { slug:"scooter-rental-bosa", alternateSlug:"noleggio-scooter-bosa", kind:"commercial", title:"Scooter Rental in Bosa | 125cc Scooters", h1:"Scooter rental in Bosa", description:"Rent a scooter in Bosa to reach Bosa Marina and explore western Sardinia. Request availability and a quote.", eyebrow:"Travel at your own pace", primaryKeyword:"scooter rental Bosa", intro:"Explore Bosa, Bosa Marina and Sardinia’s western coast with the freedom of a 125cc scooter. The service is being validated, so every request is checked for real availability, price and pickup.", sections:[{heading:"A 125cc scooter for your stay",body:["The aim is to offer practical vehicles for local journeys, with equipment and conditions communicated before confirmation."],bullets:["Model confirmed in the quote","Safety equipment to be verified","Breakdown procedure supplied in writing"]},{heading:"How it works",body:["Send an enquiry, receive a proposal and confirm only after reading the pickup, coverage and rental conditions."],bullets:["1. Send dates and quantities","2. Receive availability and price","3. Check documents and terms","4. Confirm with the provider"]},{heading:"Documents and requirements",body:["Licence, ID, payment method, deposit and age rules must be checked before confirmation. Conditions will be confirmed in the quote."]},{heading:"From the old town to the marina",body:["A scooter can suit travellers who want to alternate between the centre, Bosa Marina and coastal stops. Always account for weather, road conditions and your riding experience."]}], faq},
  { slug:"scooter-rental-bosa-marina", alternateSlug:"noleggio-scooter-bosa-marina", kind:"commercial", title:"Scooter Rental in Bosa Marina | Check availability", h1:"Scooter rental in Bosa Marina", description:"Staying in Bosa Marina? Check scooter availability and confirm pickup, possible delivery and conditions.", eyebrow:"For guests staying by the sea", primaryKeyword:"scooter rental Bosa Marina", intro:"Add your accommodation to the enquiry so pickup or possible delivery can be checked. Neither option is guaranteed before the written quote.", sections:[{heading:"Between the marina and old town",body:["A scooter may offer flexibility, but the exact pickup point and logistics must be confirmed."],bullets:["Accommodation field in the form","Delivery is not guaranteed","All details confirmed in writing"]},{heading:"Beaches and nearby places",body:["Check routes, weather, road conditions and parking rules before every journey. Our guides are starting points, not real-time local advice."]}], faq},
  { slug:"prices", alternateSlug:"prezzi", kind:"prices", title:"Bosa Scooter Rental Prices | Quote required", h1:"Prices and conditions", description:"What shapes scooter rental prices in Bosa: duration, vehicle, season, coverage and logistics.", eyebrow:"A transparent quote", primaryKeyword:"Bosa scooter rental prices", intro:"We will not publish a fictional starting price. During validation, every price must be confirmed with the vehicle, coverage, deposit and pickup method.", sections:[{heading:"What can affect the price",body:["Duration, season, vehicle, insurance options, accessories and logistics can affect the total."],bullets:["Dates and season","Vehicle and equipment","Coverage and excess","Pickup or possible delivery"]},{heading:"What a quote should include",body:["Ask for the total, deposit, fuel policy, mileage, assistance, cancellation terms and extras before you confirm."]}], faq},
  { slug:"how-it-works", alternateSlug:"come-funziona", kind:"info", title:"How scooter rental works in Bosa", h1:"How it works", description:"From availability request to confirmation: the steps for arranging a scooter in Bosa.", eyebrow:"Four clear steps", primaryKeyword:"how to rent a scooter in Bosa", intro:"This website collects qualified enquiries; it does not process automatic bookings or payments.", sections:[{heading:"1. Send the essentials",body:["Dates, scooters, riders and contact details allow a realistic check."]},{heading:"2. Receive a proposal",body:["Availability, price, model, pickup point and terms should arrive before confirmation."]},{heading:"3. Check documents and coverage",body:["Review licence rules, deposit, insurance, excess and assistance."]},{heading:"4. Confirm knowingly",body:["Submitting the form does not automatically hold a scooter."]}], faq},
  { slug:"faq", alternateSlug:"domande-frequenti", kind:"info", title:"Bosa scooter rental FAQ", h1:"Frequently asked questions", description:"Licence, documents, passenger, deposit, pickup and support: what to check before renting a scooter in Bosa.", eyebrow:"Before you ride", primaryKeyword:"Bosa scooter rental questions", intro:"The provider’s written proposal will always contain the definitive conditions.", sections:[{heading:"Details that still need confirmation",body:["We do not invent operational rules, prices or coverage. Use these answers as a checklist for your quote."]}], faq},
  { slug:"contact", alternateSlug:"contatti", kind:"contact", title:"Contact | Scooter Bosa", h1:"Request availability", description:"Send your dates and trip details to check scooter availability in Bosa or Bosa Marina.", eyebrow:"No-obligation enquiry", primaryKeyword:"Bosa scooter contact", intro:"Complete the form to receive availability, price and pickup information. Sending it is not a booking.", sections:[{heading:"Before you send",body:["The more useful context you provide, the more accurate the response can be. Never put ID, licence or payment details in the notes."]}]},
  { slug:"guides", alternateSlug:"guide", kind:"info", title:"Guides to Bosa and the western coast", h1:"Local guides", description:"Practical guides for planning travel around Bosa, Bosa Marina and western Sardinia.", eyebrow:"Useful travel planning", primaryKeyword:"Bosa travel guides", intro:"Starter content that should be reviewed with local knowledge and current sources before public launch.", sections:[{heading:"Plan with current information",body:["Weather, roads, rules and services change. Always verify actual conditions before leaving."]}]},
  { slug:"guides/visit-bosa-without-a-car", alternateSlug:"guide/visitare-bosa-senza-auto", kind:"guide", title:"Visit Bosa without a car: practical guide", h1:"How to visit Bosa without a car", description:"Plan a car-free stay in Bosa: old town, marina, transport options and when a scooter may help.", eyebrow:"Local guide", primaryKeyword:"visit Bosa without a car", intro:"A car-free break is realistic when accommodation, arrival and daily travel are planned. A scooter can broaden your options but is not the only answer.", updatedAt:"2026-08-02", sections:[{heading:"Choose where to stay",body:["The centre and marina suit different plans. Check the actual distance from the places you expect to visit."]},{heading:"Walking, public transport or scooter",body:["Walking works for compact areas; public transport must be checked against official timetables; scooters add flexibility for experienced riders."]},{heading:"When a scooter makes sense",body:["It can help connect the centre, marina and nearby stops. Consider weather, luggage and safety."]}], faq:faq.slice(0,2)},
  { slug:"guides/getting-around-bosa", alternateSlug:"guide/come-muoversi-a-bosa", kind:"guide", title:"Getting around Bosa and Bosa Marina", h1:"Getting around Bosa", description:"Compare walking, public transport, car and scooter options between Bosa and Bosa Marina.", eyebrow:"Local guide", primaryKeyword:"getting around Bosa", intro:"The best option depends on your accommodation, season, itinerary and riding confidence.", updatedAt:"2026-08-02", sections:[{heading:"Short local journeys",body:["The historic centre rewards slow exploration. Check accessibility and walking routes on arrival."]},{heading:"Between Bosa and Bosa Marina",body:["Verify transport frequencies for your dates. A scooter may add flexibility when riding conditions suit you."]},{heading:"Choose for the day",body:["Wind, rain, heat and traffic matter. Keep a sensible alternative."]}], faq:faq.slice(0,2)},
  { slug:"guides/beaches-near-bosa-by-scooter", alternateSlug:"guide/spiagge-da-raggiungere-in-scooter-da-bosa", kind:"guide", title:"Beaches near Bosa by scooter: planning guide", h1:"Reaching beaches near Bosa by scooter", description:"How to plan a beach day near Bosa by scooter without relying on invented travel times or parking claims.", eyebrow:"Local guide", primaryKeyword:"beaches near Bosa by scooter", intro:"The coast offers many possibilities, but access, parking and road conditions require current checks. This guide provides a safe planning method.", updatedAt:"2026-08-02", sections:[{heading:"Before choosing a beach",body:["Check forecasts, wind, access, services and parking rules using current sources."]},{heading:"Prepare the scooter",body:["Check fuel, helmets, storage and assistance contacts. Do not leave valuables on the vehicle."]},{heading:"Allow time for the return",body:["Plan to return with enough daylight and avoid improvised routes."]}], faq:faq.slice(1,3)},
  { slug:"guides/bosa-alghero-scooter-route", alternateSlug:"guide/itinerario-in-scooter-bosa-alghero", kind:"guide", title:"Bosa to Alghero by scooter: what to consider", h1:"Bosa–Alghero scooter route", description:"A cautious planning guide for assessing the scenic route between Bosa and Alghero by scooter.", eyebrow:"Local guide", primaryKeyword:"Bosa Alghero scooter route", intro:"Only consider this route with a suitable vehicle, experience and weather. Verify restrictions and conditions on the day.", updatedAt:"2026-08-02", sections:[{heading:"Decide whether it suits you",body:["Consider experience, passenger, range, wind and road conditions. The rental provider must confirm the route is allowed."]},{heading:"Checks before leaving",body:["Verify fuel, tyres, forecast and assistance contacts. Share your plan with someone."]},{heading:"Safety before scenery",body:["Postpone the trip if conditions are unsuitable. This guide does not replace official advice."]}], faq:faq.slice(0,3)},
];
